title: Minimal example of github pages blog with math 
author: Dave Biagioni
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Create a simple blog with math and code via Markdown and github pages.  

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  davebiagioni # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

